version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contacts-api
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    restart: unless-stopped